// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqrqdtjupeoyriptfgiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxcnFkdGp1cGVveXJpcHRmZ2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODM3MjIsImV4cCI6MjA2NDg1OTcyMn0.O_tPfqnA3N-0u29jyMkfFT4tGk3CmVfc_BLwMEyEg_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);